import type { Metadata } from "next";
import { Poppins as Font } from "next/font/google";
import "./globals.css";

const { className } = Font({ subsets: ["latin"], weight: ["800", "600", "400"] });

export const metadata: Metadata = {
  title: "Notes App FullStack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body {...[className]}>{children}</body>
    </html>
  );
}
