import type { Metadata } from "next";
import { Poppins as Font } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const font = Font({ subsets: ["latin"], weight: ["800", "600", "400"] });

export const metadata: Metadata = {
  title: "Notes App FullStack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const className = clsx(font.className, 'bg-san-juan-950 [&>*]:text-white flex items-center justify-center w-screen min-h-screen py-10')

  return (
    <html lang="en">
      <body className={className}>{children}</body>
    </html>
  );
}
